/**
 * Generated by scripts/generate-admin-credentials.mjs — do not edit by hand.
 * Source: ADMIN_PASSWORD from .env (local) or GitHub Actions secret (CI).
 */
export const ADMIN_PASSWORD_HASH = '';
