/**
 * Generated by scripts/generate-admin-credentials.mjs — do not edit by hand.
 * Source: ADMIN_GITHUB_TOKEN from .env (local) or GitHub Environment/Actions secret (CI).
 *
 * Note: a write token in a static site can be extracted from the built JS.
 * Use a fine-grained token limited to Contents write on this repo only.
 */
export const ADMIN_GITHUB_TOKEN = '';
export const ADMIN_GITHUB_OWNER = 'Emmanuel-Ratemo';
export const ADMIN_GITHUB_REPO = 'bakery';
